export const GET_ALL_DATA_START="GET_ALL_DATA_Start";
export const  GET_ALL_DATA_SUCCESS="GET_ALL_DATA_SUCCESS";


export const SEARCH_DATA_START="SEARCH_DATA_START";
export const SEARCH_DATA_SUCCESS="SEARCH_DATA_SUCCESS";


