import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react';
import { useAppContext } from '../../context/appContext';
import Wrapper from '../../components/Wrapper';


export default function Home() {
  const { results,getAllData } = useAppContext();
  useEffect(() => {
    getAllData();
  }, []);


  return (
    <>
      <Head>
        <title>Estarta Frontend Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <div>
         <Wrapper/>
       </div>
      </main>
    </>
  )
}
